### ISSUE TITLE
Cannot add endpoint

### ISSUE THREAD

**Issue by teobais** [jacobmoe/planb#8] opened 2015-06-01 00:51 UTC
Hello, I'm new to node.js and I as I have wasted much time over the net, trying to solve my problem, I thought referring here.

So, here's what I'm getting when I try to add the endpoint, mentioned on the readme file of the project:
![image](https://cloud.githubusercontent.com/assets/5684688/7904736/0548c290-0811-11e5-96be-72571ae84d0b.png)

Could anyone help me solve it?
- Google didn't help a lot, regarding the fore-mentioned error code

**Comment by jacobmoe** [comment] 2015-06-01 02:00
Unfortunately, I didn't test this on a windows machine. It looks like this is bug caused by the use of `process.env.HOME` to locate the data directory. This should fix it: http://stackoverflow.com/a/9081436/1729166 

I'll push out a fix shortly.

**Comment by jacobmoe** [comment] 2015-06-01 02:34
@toubou91 Try updating

**Comment by teobais** [comment] 2015-06-01 11:21
@jacobmoe seems like this is correct somehow, as it now tries to access user's HOME:
![image](https://cloud.githubusercontent.com/assets/5684688/7911635/7cc0c726-0868-11e5-9fd1-ec8f2a40ec05.png)

, but I'm getting the same error. I supposed this had to do with my global installation:
![image](https://cloud.githubusercontent.com/assets/5684688/7911686/30e52b7a-0869-11e5-883c-df79a77d7d3d.png)

So, I tried installing it locally, but results are still erroneous:
![image](https://cloud.githubusercontent.com/assets/5684688/7911719/64b42820-0869-11e5-87bb-e15b108cbebe.png)

![image](https://cloud.githubusercontent.com/assets/5684688/7911728/76aa4c12-0869-11e5-9d1b-695f86fc5ebb.png)

Any new ideas?

**Comment by jacobmoe** [comment] 2015-06-01 13:18
To encode the URL to a filename I'm replacing slashes with colons. Turns out that colons aren't a legal character for Windows filenames. Fixing this will be a breaking change for unixy systems. I've been working on a bunch of breaking changes anyway, so I'd like to roll a fix for this into them. 

One temporary, backwards compatible fix would be to start using some other character that is valid for Windows, and look for colons and that character when decoding. I'll try to push something out soon. 

The code in question is here: https://github.com/jacobmoe/planb/blob/master/src/lib/storage/utils.js#L28-L36

Feel free to fork and make a pull request for this if you get a chance.

**Comment by jacobmoe** [comment] 2015-06-11 13:28
`v1.0.2` eliminates the issue that we're seeing here. @toubou91, try `npm update planb -g` now. Still haven't had a chance to do much a testing on windows, so open a new ticket if it's still not working for you.

**Closed as completed by jacobmoe** 2015-06-11 13:28 UTC

**Comment by teobais** [comment] 2015-06-11 18:17
It's fine now, thanks!
(nevertheless, I just wanted to contribute, but at this time, there isn't time to even learn the basics of nodejs and npm :) )
